# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [ ]:
import pandas as pd
# Dataset 1: Product details
df1 = pd.DataFrame({
    "ProductID": [101, 102, 103],
    "ProductName": ["Pen", "Notebook", "Marker"],
    "Price": [10, 50, 30]
})


# Dataset 2: More products (same columns as df1 → good for vertical stacking)
df2 = pd.DataFrame({
    "ProductID": [104, 105],
    "ProductName": ["Pencil", "Eraser"],
    "Price": [5, 8]
})
# Dataset 3: Additional info (different columns → good for horizontal stacking)
df3 = pd.DataFrame({
    "Stock": [100, 60, 80],
    "Rating": [4.5, 4.7, 4.8]
})

In [ ]:
pd.concat([df1,df2],ignore_index=True)

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      8

In [ ]:
pd.concat([df1,df3])

   ProductID ProductName  Price  Stock  Rating
0      101.0         Pen   10.0    NaN     NaN
1      102.0    Notebook   50.0    NaN     NaN
2      103.0      Marker   30.0    NaN     NaN
0        NaN         NaN    NaN  100.0     4.5
1        NaN         NaN    NaN   60.0     4.7
2        NaN         NaN    NaN   80.0     4.8

In [ ]:
pd.concat([df1,df3],axis=1)

   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     60     4.7
2        103      Marker     30     80     4.8

In [ ]:
pd.concat([df1,df3],axis=1,ignore_index=False)

   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     60     4.7
2        103      Marker     30     80     4.8

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [ ]:
products=pd.concat([df1,df2],ignore_index=True)
products

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      8

In [ ]:
sales = pd.DataFrame({
    "ProductID": [101, 102, 104, 106],  # 106 doesn't exist in products
    "UnitsSold": [500, 200, 150, 50]
})
sales

   ProductID  UnitsSold
0        101        500
1        102        200
2        104        150
3        106         50

In [ ]:
pd.merge(products,sales)

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

In [16]:
pd.merge(products,sales, on= "ProductID")

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

In [17]:
pd.merge(products,sales, on= "ProductID",how="left")

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10      500.0
1        102    Notebook     50      200.0
2        103      Marker     30        NaN
3        104      Pencil      5      150.0
4        105      Eraser      8        NaN

In [19]:
pd.merge(products,sales, on= "ProductID",how="right")

   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0        500
1        102    Notebook   50.0        200
2        104      Pencil    5.0        150
3        106         NaN    NaN         50

In [20]:
pd.merge(products,sales, on= "ProductID",how="outer")

   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0      500.0
1        102    Notebook   50.0      200.0
2        103      Marker   30.0        NaN
3        104      Pencil    5.0      150.0
4        105      Eraser    8.0        NaN
5        106         NaN    NaN       50.0

In [21]:
pd.merge(products,sales, on= "ProductID",how="inner")

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [23]:
products=pd.concat([df1,df2],ignore_index=True)
products

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      8

In [24]:
stock = pd.DataFrame({
    "Stock": [100, 60, 80, 120, 150],
}, index=[101, 102, 103, 104, 105])

     Stock
101    100
102     60
103     80
104    120
105    150

In [31]:
p_dataset=products.set_index("ProductID")
p_dataset

          ProductName  Price
ProductID
101               Pen     10
102          Notebook     50
103            Marker     30
104            Pencil      5
105            Eraser      8

In [32]:
p_dataset.join(stock)

          ProductName  Price  Stock
ProductID
101               Pen     10    100
102          Notebook     50     60
103            Marker     30     80
104            Pencil      5    120
105            Eraser      8    150

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

In [38]:
import pandas as pd
# sales data
sales = pd.DataFrame({
    "ProductID": [201, 202, 203, 204],
    "UnitsSold": [500, 300, 400, 250]
})

# Revenue data (missing ProductID 204, extra 205)
revenue = pd.DataFrame({
    "ProductID": [201, 202, 203, 205],
    "Revenue": [7500, 4500, 6800, 1200]
})
merged_data_frame=pd.merge(sales,revenue, on="ProductID" ,how="outer")
merged_data_frame

   ProductID  UnitsSold  Revenue
0        201      500.0   7500.0
1        202      300.0   4500.0
2        203      400.0   6800.0
3        204      250.0      NaN
4        205        NaN   1200.0

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [48]:
import pandas as pd
# 1. Create three DataFrames: Products, Sales, and Revenue
products = pd.DataFrame({
    "ProductID": [101, 102, 103, 104],
    "ProductName": ["Pen", "Notebook", "Pencil", "Eraser"]
})
sales = pd.DataFrame({
    "ProductID": [101, 102, 103, 105],
    "UnitsSold": [200, 150, 300, 50]
})
revenue = pd.DataFrame({
    "ProductID": [101, 102, 104, 105],
    "Revenue": [1000, 2500, 800, 200]
})
# 2. Concatenate them vertically and horizontally
# Write your code here
print("\n Vertical concatenation")
vertical=pd.concat([products,sales,revenue],axis=0,ignore_index=True)
print(vertical)
print("\nHorizontal concatenation")
horizontal=pd.concat([products,sales,revenue],axis=1,ignore_index=True)
print(horizontal)

# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here
print("\n Merge sales revenue using inner join")
inner_join=pd.merge(sales,revenue,on="ProductID", how="inner")
print(inner_join)

print("\n Merge sales revenue using left join")
left_join=pd.merge(sales,revenue,on="ProductID",how="left")
print(left_join)

print("\n Merge sales revenue using right join")
right_join=pd.merge(sales,revenue,on="ProductID",how="right")
print(right_join)

print("\n Merge sales revenue using outer join")
outer_join=pd.merge(sales,revenue,on="ProductID",how="outer")
print(outer_join)

# 4. Join Products with Sales based on index or a key
# Write your code here
print("\n Joining based on index")
index_join=products.set_index("ProductID").join(sales.set_index("ProductID"))
print(index_join)
# 5. Analyze missing values after joins

# Use isna(), info(), or describe() to explore gaps
# Write your code here

 Vertical concatenation
    ProductID ProductName  UnitsSold  Revenue
0         101         Pen        NaN      NaN
1         102    Notebook        NaN      NaN
2         103      Pencil        NaN      NaN
3         104      Eraser        NaN      NaN
4         101         NaN      200.0      NaN
5         102         NaN      150.0      NaN
6         103         NaN      300.0      NaN
7         105         NaN       50.0      NaN
8         101         NaN        NaN   1000.0
9         102         NaN        NaN   2500.0
10        104         NaN        NaN    800.0
11        105         NaN        NaN    200.0

Horizontal concatenation
     0         1    2    3    4     5
0  101       Pen  101  200  101  1000
1  102  Notebook  102  150  102  2500
2  103    Pencil  103  300  104   800
3  104    Eraser  105   50  105   200

 Merge sales revenue using inner join
   ProductID  UnitsSold  Revenue
0        101        200     1000
1        102        150     2500
2        105         50      200

 Merge sales revenue using left join
   ProductID  UnitsSold  Revenue
0        101        200   1000.0
1        102        150   2500.0
2        103        300      NaN
3        105         50    200.0

 Merge sales revenue using right join
   ProductID  UnitsSold  Revenue
0        101      200.0     1000
1        102      150.0     2500
2        104        NaN      800
3        105       50.0      200

 Merge sales revenue using outer join
   ProductID  UnitsSold  Revenue
0        101      200.0   1000.0
1        102      150.0   2500.0
2        103      300.0      NaN
3        104        NaN    800.0
4        105       50.0    200.0

 Joining based on index
          ProductName  UnitsSold
ProductID
101               Pen      200.0
102          Notebook      150.0
103            Pencil      300.0
104            Eraser        NaN

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.