# 🐼 Pandas - Class 8: Working with Time Series
Welcome to **Class 8** of our Pandas series. Today we’ll learn how to handle and analyze time series data.

## 1. Converting Columns to Datetime (`pd.to_datetime`)
- Use `pd.to_datetime()` to convert strings or numbers into datetime objects.
- Once converted, Pandas recognizes them as dates, enabling powerful operations.

In [25]:
import pandas as pd
data = {
    "orderID": [101, 102, 103, 104, 105, 106],
    "order_Date": ["2024-01-10", "2024-03-12", "2024-06-15", "2024-01-18", "2024-01-20", "2024-01-22"],
    "Customer": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "Amount": [250, 400, 150, 300, 500, 350]
}
df=pd.DataFrame(data)
df

   orderID  order_Date Customer  Amount
0      101  2024-01-10    Alice     250
1      102  2024-03-12      Bob     400
2      103  2024-06-15  Charlie     150
3      104  2024-01-18    Alice     300
4      105  2024-01-20    David     500
5      106  2024-01-22      Bob     350

In [26]:
df['order_Date']=pd.to_datetime(df["order_Date"],errors="coerce")

In [27]:
df

   orderID order_Date Customer  Amount
0      101 2024-01-10    Alice     250
1      102 2024-03-12      Bob     400
2      103 2024-06-15  Charlie     150
3      104 2024-01-18    Alice     300
4      105 2024-01-20    David     500
5      106 2024-01-22      Bob     350

## 2. Setting DateTime Index & Resampling
- Set a datetime column as the index with `set_index()`.
- Resample time series using `resample('M').mean()` or other rules ('D', 'W', 'Y').
- Useful for aggregating data by time periods.

In [32]:
df_idx=df.set_index("order_Date")
df_idx.resample("Y")["Amount"].sum()

/tmp/ipykernel_304/3773862888.py:2: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  df_idx.resample("Y")["Amount"].sum()

order_Date
2024-12-31    1950
Freq: YE-DEC, Name: Amount, dtype: int64

## mini-project

Converting columns to datetime (pd.to_datetime)

Setting a DateTime index & resampling

In [46]:
import pandas as pd
# 1️⃣ Create a dataset of website visits (string dates + visit counts)
data = {
    "Date": [
        "2024-01-01", "2024-01-02", "2024-01-03",
        "2024-01-05", "2024-01-07", "2024-01-10",
        "2024-01-12", "2024-01-15", "2024-01-18",
        "2024-01-20"
    ],
    "Visits": [120, 150, 130, 170, 160, 200, 190, 210, 180, 220]
}
df=pd.DataFrame(data)
print(df)
# 2️⃣ Convert VisitDate to datetime
# Write your code here
df["Date"]=pd.to_datetime(df["Date"])
print(df)
# 3️⃣ Set VisitDate as the index
# Write your code here
df_idx=df.set_index("Date")
print(df_idx)

# 4️⃣ Resample to get total visitors per month
# Write your code here
df_idx.resample("ME").count()

# 5️⃣ Resample to get average visitors per week
# Write your code here
df_idx.resample("W").mean()

         Date  Visits
0  2024-01-01     120
1  2024-01-02     150
2  2024-01-03     130
3  2024-01-05     170
4  2024-01-07     160
5  2024-01-10     200
6  2024-01-12     190
7  2024-01-15     210
8  2024-01-18     180
9  2024-01-20     220
        Date  Visits
0 2024-01-01     120
1 2024-01-02     150
2 2024-01-03     130
3 2024-01-05     170
4 2024-01-07     160
5 2024-01-10     200
6 2024-01-12     190
7 2024-01-15     210
8 2024-01-18     180
9 2024-01-20     220
            Visits
Date
2024-01-01     120
2024-01-02     150
2024-01-03     130
2024-01-05     170
2024-01-07     160
2024-01-10     200
2024-01-12     190
2024-01-15     210
2024-01-18     180
2024-01-20     220

                Visits
Date
2024-01-07  146.000000
2024-01-14  195.000000
2024-01-21  203.333333

---
## Summary
- Converted columns to datetime with `pd.to_datetime`.
- Set DateTime index and resampled data.
- Performed date-based filtering and slicing.
- Applied rolling and expanding window calculations.