# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [12]:
import numpy as np
import pandas as pd
a={
    "Name":["Alice","Bob","Charlie","John","David"],
    "Age":[55,33,24,67,12],
    "Marks":[77,56,45,39,28]
}
df=pd.DataFrame(a)
df

      Name  Age  Marks
0    Alice   55     77
1      Bob   33     56
2  Charlie   24     45
3     John   67     39
4    David   12     28

In [13]:
df[df["Age"]>30]

    Name  Age  Marks
0  Alice   55     77
1    Bob   33     56
3   John   67     39

In [21]:
df[(df['Age']>50) & (df['Marks']>35) ]

    Name  Age  Marks
0  Alice   55     77
3   John   67     39

In [22]:
df[(df['Age']>50) | (df['Marks']>45) ]

    Name  Age  Marks
0  Alice   55     77
1    Bob   33     56
3   John   67     39

In [24]:
df[(df['Age']>50) ^ (df['Marks']>45) ]

   Name  Age  Marks
1   Bob   33     56
3  John   67     39

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [25]:
df.query("Age>44")

    Name  Age  Marks
0  Alice   55     77
3   John   67     39

In [26]:
df.query("Age<55 and Marks >55")

  Name  Age  Marks
1  Bob   33     56

In [28]:
hold=50
df.query("Age> @hold")

    Name  Age  Marks
0  Alice   55     77
3   John   67     39

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [31]:
df["Name"].str.upper()

0      ALICE
1        BOB
2    CHARLIE
3       JOHN
4      DAVID
Name: Name, dtype: object

In [34]:
df["Name"].str.contains("a",case=False)

0     True
1    False
2     True
3    False
4     True
Name: Name, dtype: bool

In [35]:
df["Name"].str.replace("Alice","Avnish")

0     Avnish
1        Bob
2    Charlie
3       John
4      David
Name: Name, dtype: object

In [39]:
df[df["Name"].str.startswith("A")]

    Name  Age  Marks
0  Alice   55     77

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [49]:
import pandas as pd

# 1. Build a DataFrame with columns: Name, Age, City, Score
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore"],
    "Score": [85, 90, 78, 88]
}
df=pd.DataFrame(data)
df

# 2. Use boolean indexing to select rows where Age > 25
# Write your code here
df[df["Age"]>25]

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here
df[(df['City']=="Delhi") | (df['City']=="Mumbai")]

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here
df.query("Score >=85 and Age <35")

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here
df["City"]=df["City"].str.replace("Delhi","New Delhi")
df["City"]=df["City"].str.lower()
df

      Name  Age       City  Score
0    Alice   25  new delhi     85
1      Bob   30     mumbai     90
2  Charlie   35       pune     78
3    David   40  bangalore     88

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.