# 🐼 Pandas - Class 2: DataFrame Basics
Welcome to **Class 2**. Today we’ll learn how to **inspect**, **select**, and **organize** data inside a DataFrame.

## 1 Inspecting Data
Quick ways to understand your dataset:
- `head(n)` → first *n* rows (default 5)
- `tail(n)` → last *n* rows
- `info()` → columns, non-null counts, and dtypes
- `shape` → (rows, columns)
- `dtypes` → data type of each column

In [1]:
import pandas as pd

# Create a small DataFrame
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
#b.head()
#b.tail(1)
#b.info()
#b.shape
b.dtypes

Name     object
Age       int64
Score     int64
dtype: object

## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:
- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]`
Tip: `:` means "all rows/columns" in that dimension.

In [8]:

#b['Name'] for selecting a single column
#b[['Name', 'Age']] for selecting multiple colums , Fancy indexing
#b.loc[0,"Age"] for selecting on the basis of row
#b.loc[1:3,["Name","Age","Score"]]

      Name  Age  Score
1      Bob   30     92
2  Charlie   35     79
3    David   40     85

## 3 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array (read-only; prefer using DataFrame ops)

In [11]:
#b.index  - to list start , stop and step
#b.columns - to show all the colums in dataset
#b.values - to show all the values

array([['Alice', 25, 88],
       ['Bob', 30, 92],
       ['Charlie', 35, 79],
       ['David', 40, 85],
       ['Emma', 22, 95]], dtype=object)

## 4 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as index → `df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)`
 If you don't use `inplace=True`, remember to assign the result back to a variable.

In [13]:

c=b.rename(columns={"Score":"Marks"})
d=c.set_index("Name",inplace=False)
d

         Age  Marks
Name
Alice     25     88
Bob       30     92
Charlie   35     79
David     40     85
Emma      22     95

## 5 Basic Attributes Recap
- `df.columns` → names of all columns
- `df.index` → row labels
- `df.values` → NumPy array (data only)
These are handy for quick checks and loops (though vectorized ops are preferred).

## Mini Practice
1. Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
2. Show the first 3 rows, last 2 rows, and the info.
3. Select a sub-DataFrame with only 2 columns.
4. Rename one column and set any column as index, then reset it back.
5. Print `df.shape`, `df.dtypes`, and `df.columns`.

In [35]:
import pandas as pd

# Create a DataFrame with at least 5 rows & 4 columns (mix of numbers + text)
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)

# Show the first 3 rows, last 2 rows, and info
# your code here

#df.head(3)
#df.tail(2)
#df.info()

# Select a sub-DataFrame with only 2 columns
# your code here
# df[["Name","Age"]]


# Rename one column and set any column as index, then reset it back
# your code here
c=df.rename(columns={"Score":"Marks"},inplace=False)
c.set_index("Name")
c.reset_index(inplace=True)


# Print df.shape, df.dtypes, and df.columns
# your code here
print(df.shape)
print(df.dtypes)
print(df.columns)

(5, 4)
Name     object
Age       int64
City     object
Score     int64
dtype: object
Index(['Name', 'Age', 'City', 'Score'], dtype='object')

---
## ✅ Summary
- You learned to **inspect** a DataFrame (`head`, `tail`, `info`, `shape`, `dtypes`).
- You practiced **selecting** columns/rows using `[]`, `.loc`, and `.iloc`.
- You explored **index/columns** and basic attributes.
- You **renamed** columns and **set/reset** an index.

Next up: **Data Cleaning Essentials** (missing values, types, duplicates).