# 🐼 Pandas - Class 5: Sorting & Basic Statistics
Welcome to **Class 5** of our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [2]:
import pandas as pd
data={
     "Products":["Pen","Notebook","Pencil","Marker","Eraser","Sharpener"],
     "Price":[10,50,5,30,8,12],
     "Stock":[100,60,200,80,150,120],
     "Rating":[4.5,4.7,4.2,4.8,4.3,4.4]
}
df=pd.DataFrame(data)
df

    Products  Price  Stock  Rating
0        Pen     10    100     4.5
1   Notebook     50     60     4.7
2     Pencil      5    200     4.2
3     Marker     30     80     4.8
4     Eraser      8    150     4.3
5  Sharpener     12    120     4.4

In [3]:
df.sort_values(by="Price")  # for sorting values of a particular column in ascending order

    Products  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7

In [4]:
df.sort_values(by="Price",ascending=False)

    Products  Price  Stock  Rating
1   Notebook     50     60     4.7
3     Marker     30     80     4.8
5  Sharpener     12    120     4.4
0        Pen     10    100     4.5
4     Eraser      8    150     4.3
2     Pencil      5    200     4.2

In [5]:
#sort by multiple colums (price ascending order , Stock descending)
df.sort_values(by=["Price","Stock"],ascending=[True,False])

    Products  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [6]:
df.mean(numeric_only=True)

Price      19.166667
Stock     118.333333
Rating      4.483333
dtype: float64

In [7]:
df.median(numeric_only=True)

Price      11.00
Stock     110.00
Rating      4.45
dtype: float64

In [8]:
df.mode()

    Products  Price  Stock  Rating
0     Eraser      5     60     4.2
1     Marker      8     80     4.3
2   Notebook     10    100     4.4
3        Pen     12    120     4.5
4     Pencil     30    150     4.7
5  Sharpener     50    200     4.8

In [9]:
df.std(numeric_only=True)

Price     17.486185
Stock     50.760877
Rating     0.231661
dtype: float64

In [10]:
df.describe()

           Price       Stock    Rating
count   6.000000    6.000000  6.000000
mean   19.166667  118.333333  4.483333
std    17.486185   50.760877  0.231661
min     5.000000   60.000000  4.200000
25%     8.500000   85.000000  4.325000
50%    11.000000  110.000000  4.450000
75%    25.500000  142.500000  4.650000
max    50.000000  200.000000  4.800000

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [13]:
df["Products"].value_counts()

Products
Pen          1
Notebook     1
Pencil       1
Marker       1
Eraser       1
Sharpener    1
Name: count, dtype: int64

In [14]:
df["Products"].value_counts(normalize=True)

Products
Pen          0.166667
Notebook     0.166667
Pencil       0.166667
Marker       0.166667
Eraser       0.166667
Sharpener    0.166667
Name: proportion, dtype: float64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [17]:
df.corr(numeric_only=True)

           Price     Stock    Rating
Price   1.000000 -0.804028  0.820402
Stock  -0.804028  1.000000 -0.921257
Rating  0.820402 -0.921257  1.000000

In [18]:
df["Price"].corr(df["Rating"])

np.float64(0.8204016469535791)

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [29]:
# Write your mini practice solution here
import pandas as pd
# 1. Build a DataFrame with columns: Name, Age, Score, Height
data={
    "Name":["Alice","Bob","Charlie","David","Emaa"],
    "Age":[25,30,45,40,22],
    "Score":[88,92,79,85,95],
    "Height":[160,175,168,180,158]
}
df=pd.DataFrame(data)

# 2. Sort the data by Score (descending)
# Write your code here
df.sort_values(by="Score",ascending=False)
# 3. Get mean, median, mode, and std of numeric columns
# Write your code here
df.mean(numeric_only=True)
df.median(numeric_only=True)
df.mode()
df.std(numeric_only=True)
df.describe()
# 4. Use value_counts on Name or any categorical column
# Write your code here
df["Name"].value_counts()

# 5. Compute corr() and cov() for all numeric columns
# Write your code here
df.corr(numeric_only=True)
df.cov(numeric_only=True)

          Age  Score  Height
Age     96.30 -54.65   59.40
Score  -54.65  38.70  -19.45
Height  59.40 -19.45   89.20

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.