# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [4]:
import pandas as pd
data={
    "Employee":["John","Sarah","Mike","Anna","Tom","Laura","Steve","Kate"],
    "Department":["HR","IT","IT","Finance","Finance","HR","IT","Finance"],
    "Salary":[50000,70000,72000,65000,60000,52000,75000,58000]
}
df=pd.DataFrame(data)
df

  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [6]:
df["Department"].value_counts()

Department
IT         3
Finance    3
HR         2
Name: count, dtype: int64

In [8]:
df.groupby("Department")["Salary"].mean()

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

In [12]:
df.groupby("Department")["Employee"].count()

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [14]:
df.groupby("Department")["Salary"].agg(["mean","min","max"])

                    mean    min    max
Department
Finance     61000.000000  58000  65000
HR          51000.000000  50000  52000
IT          72333.333333  70000  75000

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [17]:
df.groupby("Department")["Salary"].agg(["min","max","sum","mean"])

              min    max     sum          mean
Department
Finance     58000  65000  183000  61000.000000
HR          50000  52000  102000  51000.000000
IT          70000  75000  217000  72333.333333

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [20]:
data={
    "Employee":["John","Sarah","Mike","Anna","Tom","Laura","Steve","Kate"],
    "Department":["HR","IT","IT","Finance","Finance","HR","IT","Finance"],
    "Salary":[50000,70000,72000,65000,60000,52000,75000,58000],
    "Age":[28,32,30,27,35,29,31,26]
}
df=pd.DataFrame(data)
df

  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [23]:
df.groupby("Department").agg({
    "Salary":["mean","max","min"],
    "Age":["mean","max"]
})

                  Salary                      Age
                    mean    max    min       mean max
Department
Finance     61000.000000  65000  58000  29.333333  35
HR          51000.000000  52000  50000  28.500000  29
IT          72333.333333  75000  70000  31.000000  32

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [24]:
df.pivot_table(values=["Salary","Age"],index="Department",aggfunc="mean")

                  Age        Salary
Department
Finance     29.333333  61000.000000
HR          28.500000  51000.000000
IT          31.000000  72333.333333

In [ ]:
df.crosstab()

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [38]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
import pandas as pd
data = {
    "Department": ["HR", "IT", "Finance", "IT", "HR"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Salary": [50000, 70000, 60000, 75000, 52000],
    "Age": [25, 30, 28, 35, 26],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Delhi"]
}

df = pd.DataFrame(data)
print(df)
# 2. Group by Department to get average Salary and max Age
# Write your code here
df.groupby("Department")["Salary"].mean()
df.groupby("Department")["Age"].max()

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here
df.groupby("Department").agg({
    "Salary":["mean"],
    "Age":["max"]
})
# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here
df.pivot_table(values="Salary",index=["Department"],columns="City",aggfunc="mean",fill_value=0)

# 5. Build a crosstab for Department vs City
# Write your code here
#pd.crosstab(df["Department"],df["City"])

  Department Employee  Salary  Age       City
0         HR    Alice   50000   25      Delhi
1         IT      Bob   70000   30     Mumbai
2    Finance  Charlie   60000   28       Pune
3         IT    David   75000   35  Bangalore
4         HR      Eve   52000   26      Delhi

City        Bangalore    Delhi   Mumbai     Pune
Department
Finance           0.0      0.0      0.0  60000.0
HR                0.0  51000.0      0.0      0.0
IT            75000.0      0.0  70000.0      0.0

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.